[github_app]
pr_commands = [ "/review", "/generate_labels", "/improve" ]

[pr_reviewer]
enable_review_labels_security = true
enable_review_labels_effort = false

[pr_description]
publish_description_as_comment = true

[pr_code_suggestions]
commitable_code_suggestions = true
