[github_app]
pr_commands = [
    "/review",
]

[pr_reviewer]
enable_review_labels_security = true  # Adds 'possible security issue' label if detected
enable_review_labels_effort = true    # Adds 'Review effort [x/5]' label

